### ISSUE TITLE
Doesn't work on File DataObject

### ISSUE THREAD

**Issue by elliot-sawyer** [phptek/silverstripe-verifiable#25]
The change doesn't appear in the asset admin CMS fields
```
PhpTek\Verifiable\Backend\BackendServiceFactory:
  backend: chainpoint

SilverStripe\Assets\File:
  extensions:
    - PhpTek\Verifiable\Model\VerifiableExtension
  verifiable_fields:
    - Title
```
